services:
  suki-helper:
    image: suki-helper
    container_name: suki-helper
    expose:
      - "8080"       # nginx가 내부에서 접근할 포트

  nginx:
    image: nginx
    container_name: suki-nginx
    ports:
      - "80:80"      # 외부 접근 포트
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - suki-helper
